language: python
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y python-lxml python-pip
install:
- deactivate
- gem install kramdown-rfc2629
- gem install rake
- gem install cddl
- sudo pip install xml2rfc
script: 
- make ghpages
- rake verify
env:
  global:
  - secure: <insert encrypted GH_TOKEN=blah here>
  - secure: UxxrSOF4wfTh1Y6zkFUqfROIdOibTtWZ7qK6HY1CDdzwl2kpXaJZ0g0FMV7fSfJsrLRjbUv3jl7Ob2JSDtIsWNE1OlG0bb+IqwG4cSTU5avDFJeDwqFGRYCmoqdeEUzyXuwfzhwq+6iVmwONMXsZal6Ww3yegcENnOYX9x/GmKI=
before_deploy: make submit
deploy:
  provider: releases
  api-key:
    secure: <insert encrypted API key here>
  file:
  - $TRAVIS_TAG.txt
  - $TRAVIS_TAG.html
  - $TRAVIS_TAG.xml
  skip_cleanup: true
  on:
    branch: master
    tags: true
